language: ruby

rvm:
  - 2.0.0

before_script:
  - psql -c 'create database status_test;' -U postgres
  - bundle exec rake db:schema:load

notifications:
  email:
  - sferik@gmail.com
  - evan+notify@phx.io
  - radcliffe.david+rubygems@gmail.com
