language: ruby

rvm:
  - 2.1.7
  - 2.2.3
  - ruby-head

cache: bundler

sudo: false

before_script:
  - psql -c 'create database status_test;' -U postgres
  - bundle exec rake db:schema:load

notifications:
  email:
  - sferik@gmail.com
  - evan+notify@phx.io
  - radcliffe.david+rubygems@gmail.com
